import TelegramBot from "node-telegram-bot-api";
import { AlertData } from "../types/market.model";
import { getRSISignal } from "../utils/rsi.utils";

export class TelegramService {
  private bot: TelegramBot;
  private chatId: string;

  constructor(botToken: string, chatId: string) {
    this.bot = new TelegramBot(botToken, { polling: false });
    this.chatId = chatId;
  }

  /**
   * Send a simple text message
   */
  async sendMessage(message: string): Promise<void> {
    try {
      await this.bot.sendMessage(this.chatId, message, {
        parse_mode: "HTML",
        disable_web_page_preview: true,
      });
    } catch (error) {
      console.error("Error sending Telegram message:", error);
      throw error;
    }
  }

  /**
   * Send price and RSI alert
   */
  async sendPriceAlert(alertData: AlertData): Promise<void> {
    const { symbol, currentPrice, rsi, timestamp, timeframe } = alertData;
    const rsiSignal = getRSISignal(rsi);
    const time = new Date(timestamp).toISOString();

    const message = `
📊 <b>Price Alert - ${symbol}</b>

💰 <b>Current Price:</b> ${currentPrice.toLocaleString()} USDT
📈 <b>RSI ({timeframe}):</b> ${rsi} ${rsiSignal}
🕐 <b>Time:</b> ${time}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
<i>Alert generated by Signals Bot</i>
    `.trim();

    await this.sendMessage(message);
  }

  /**
   * Send bot startup notification
   */
  async sendStartupMessage(): Promise<void> {
    const message = `
🚀 <b>Signals Bot Started</b>

✅ Bot is now monitoring market data
⏰ Executing every minute (UTC)
📊 Tracking: Price + RSI signals
🔄 Real-time data from Binance API

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
<i>Bot started at: ${new Date().toISOString()}</i>
    `.trim();

    await this.sendMessage(message);
  }

  /**
   * Send error notification
   */
  async sendErrorMessage(error: string, context?: string): Promise<void> {
    const message = `
❌ <b>Bot Error</b>

${context ? `<b>Context:</b> ${context}\n` : ""}
<b>Error:</b> ${error}
🕐 <b>Time:</b> ${new Date().toISOString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
<i>Please check the bot logs for more details</i>
    `.trim();

    await this.sendMessage(message);
  }

  /**
   * Send health check message
   */
  async sendHealthCheck(): Promise<void> {
    const message = `
💚 <b>Bot Health Check</b>

✅ Bot is running normally
🕐 Last check: ${new Date().toISOString()}
    `.trim();

    await this.sendMessage(message);
  }

  /**
   * Test if the bot can send messages
   */
  async testConnection(): Promise<boolean> {
    try {
      await this.sendMessage("🧪 Bot connection test successful!");
      return true;
    } catch (error) {
      console.error("Telegram connection test failed:", error);
      return false;
    }
  }
}
