import TelegramBot from "node-telegram-bot-api";
import {
  AlertData,
  TradingSignal,
  MultiSignalAlert,
} from "../types/market.model";
import { getRSISignal } from "../utils/rsi.utils";

export class TelegramService {
  private bot: TelegramBot;
  private chatId: string;

  constructor(botToken: string, chatId: string) {
    this.bot = new TelegramBot(botToken, { polling: false });
    this.chatId = chatId;
  }

  /**
   * Send a simple text message
   */
  async sendMessage(message: string): Promise<void> {
    try {
      await this.bot.sendMessage(this.chatId, message, {
        parse_mode: "HTML",
        disable_web_page_preview: true,
      });
    } catch (error) {
      console.error("Error sending Telegram message:", error);
      throw error;
    }
  }

  /**
   * Send price and RSI alert
   */
  async sendPriceAlert(alertData: AlertData): Promise<void> {
    const { symbol, currentPrice, rsi, timestamp, timeframe } = alertData;
    const rsiSignal = getRSISignal(rsi);
    const time = new Date(timestamp).toISOString();

    const message = `
📊 <b>Price Alert - ${symbol}</b>

💰 <b>Current Price:</b> ${currentPrice.toLocaleString()} USDT
📈 <b>RSI (${timeframe}):</b> ${rsi} ${rsiSignal}
🕐 <b>Time:</b> ${time}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
<i>Alert generated by Signals Bot</i>
    `.trim();

    await this.sendMessage(message);
  }

  /**
   * Send bot startup notification
   */
  async sendStartupMessage(): Promise<void> {
    const message = `
🚀 <b>Multi-Signal Trading Bot Started</b>

✅ Bot is now monitoring market data
⏰ Executing every minute (UTC)
🎯 <b>RSI Divergence Detection: ENABLED</b>
📊 <b>MACD Divergence Detection: ENABLED</b>
🏗️ <b>Market Structure Detection: ENABLED</b>
🔄 Real-time data from Binance API
📱 <b>Alerts: Multi-confirmation signals only</b>
🔥 <b>High Probability Setups</b>

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
<i>Bot started at: ${new Date().toISOString()}</i>
    `.trim();

    await this.sendMessage(message);
  }

  /**
   * Send error notification
   */
  async sendErrorMessage(error: string, context?: string): Promise<void> {
    const message = `
❌ <b>Bot Error</b>

${context ? `<b>Context:</b> ${context}\n` : ""}
<b>Error:</b> ${error}
🕐 <b>Time:</b> ${new Date().toISOString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
<i>Please check the bot logs for more details</i>
    `.trim();

    await this.sendMessage(message);
  }

  /**
   * Send health check message
   */
  async sendHealthCheck(): Promise<void> {
    const message = `
💚 <b>Bot Health Check</b>

✅ Bot is running normally
🕐 Last check: ${new Date().toISOString()}
    `.trim();

    await this.sendMessage(message);
  }

  /**
   * Send trading signal with divergence detection
   */
  async sendTradingSignal(signal: TradingSignal): Promise<void> {
    const {
      symbol,
      currentPrice,
      rsi,
      divergenceSignal,
      timestamp,
      timeframe,
    } = signal;
    const rsiSignal = getRSISignal(rsi);
    const time = new Date(timestamp).toISOString();

    let message = `
📊 <b>Trading Signal - ${symbol}</b>

💰 <b>Current Price:</b> ${currentPrice.toLocaleString()} USDT
📈 <b>RSI (${timeframe}):</b> ${rsi} ${rsiSignal}
🕐 <b>Time:</b> ${time}
    `;

    // Add divergence signal if present
    if (divergenceSignal) {
      const signalType =
        divergenceSignal.type === "BULLISH" ? "🟢 BULLISH" : "🔴 BEARISH";
      const strength =
        divergenceSignal.confidence >= 80
          ? "🔥 STRONG"
          : divergenceSignal.confidence >= 60
          ? "⚡ MEDIUM"
          : divergenceSignal.confidence >= 40
          ? "💡 WEAK"
          : "❓ VERY WEAK";

      message += `

🎯 <b>DIVERGENCE SIGNAL DETECTED!</b>
${signalType} DIVERGENCE ${strength}

📊 <b>Entry Price:</b> ${divergenceSignal.price.toLocaleString()} USDT
📈 <b>RSI at Signal:</b> ${divergenceSignal.rsi.toFixed(2)}
🎯 <b>Take Profit:</b> ${divergenceSignal.takeProfit.toLocaleString()} USDT
🛡️ <b>Stop Loss:</b> ${divergenceSignal.stopLoss.toLocaleString()} USDT
📊 <b>Confidence:</b> ${divergenceSignal.confidence.toFixed(1)}%

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
<i>⚠️ This is not financial advice. Trade at your own risk.</i>
      `;
    } else {
      message += `

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
<i>Alert generated by Signals Bot</i>
      `;
    }

    await this.sendMessage(message.trim());
  }

  /**
   * Send multi-signal alert with RSI, MACD, and Market Structure
   */
  async sendMultiSignalAlert(alert: MultiSignalAlert): Promise<void> {
    const {
      symbol,
      currentPrice,
      rsi,
      macd,
      timestamp,
      timeframe,
      rsiDivergence,
      macdDivergence,
      marketStructure,
    } = alert;
    const rsiSignal = getRSISignal(rsi);
    const time = new Date(timestamp).toISOString();

    let message = `
📊 <b>Multi-Signal Alert - ${symbol}</b>

💰 <b>Current Price:</b> ${currentPrice.toLocaleString()} USDT
📈 <b>RSI (${timeframe}):</b> ${rsi} ${rsiSignal}
🕐 <b>Time:</b> ${time}
    `;

    // Add MACD data if available
    if (macd) {
      const macdTrend =
        macd.macd > macd.signal
          ? "🟢 BULLISH"
          : macd.macd < macd.signal
          ? "🔴 BEARISH"
          : "⚪ NEUTRAL";
      message += `
📊 <b>MACD:</b> ${macd.macd.toFixed(6)} | Signal: ${macd.signal.toFixed(
        6
      )} ${macdTrend}
📊 <b>Histogram:</b> ${macd.histogram.toFixed(6)}
      `;
    }

    let signalCount = 0;

    // Add RSI Divergence signal if present
    if (rsiDivergence) {
      signalCount++;
      const signalType =
        rsiDivergence.type === "BULLISH" ? "🟢 BULLISH" : "🔴 BEARISH";
      const strength =
        rsiDivergence.confidence >= 80
          ? "🔥 STRONG"
          : rsiDivergence.confidence >= 60
          ? "⚡ MEDIUM"
          : rsiDivergence.confidence >= 40
          ? "💡 WEAK"
          : "❓ VERY WEAK";

      message += `

🎯 <b>RSI DIVERGENCE DETECTED!</b>
${signalType} RSI DIVERGENCE ${strength}

📊 <b>Entry Price:</b> ${rsiDivergence.price.toLocaleString()} USDT
📈 <b>RSI at Signal:</b> ${rsiDivergence.rsi.toFixed(2)}
🎯 <b>Take Profit:</b> ${rsiDivergence.takeProfit.toLocaleString()} USDT
🛡️ <b>Stop Loss:</b> ${rsiDivergence.stopLoss.toLocaleString()} USDT
📊 <b>Confidence:</b> ${rsiDivergence.confidence.toFixed(1)}%
      `;
    }

    // Add MACD Divergence signal if present
    if (macdDivergence) {
      signalCount++;
      const signalType =
        macdDivergence.type === "BULLISH" ? "🟢 BULLISH" : "🔴 BEARISH";
      const strength =
        macdDivergence.confidence >= 80
          ? "🔥 STRONG"
          : macdDivergence.confidence >= 60
          ? "⚡ MEDIUM"
          : macdDivergence.confidence >= 40
          ? "💡 WEAK"
          : "❓ VERY WEAK";

      message += `

📊 <b>MACD DIVERGENCE DETECTED!</b>
${signalType} MACD DIVERGENCE ${strength}

📊 <b>Entry Price:</b> ${macdDivergence.price.toLocaleString()} USDT
📈 <b>MACD at Signal:</b> ${macdDivergence.macd.toFixed(6)}
🎯 <b>Take Profit:</b> ${macdDivergence.takeProfit.toLocaleString()} USDT
🛡️ <b>Stop Loss:</b> ${macdDivergence.stopLoss.toLocaleString()} USDT
📊 <b>Confidence:</b> ${macdDivergence.confidence.toFixed(1)}%
      `;
    }

    // Add Market Structure signal if present
    if (marketStructure) {
      signalCount++;
      const signalType = marketStructure.type.includes("BULLISH")
        ? "🟢 BULLISH"
        : "🔴 BEARISH";
      const strength =
        marketStructure.confidence >= 80
          ? "🔥 STRONG"
          : marketStructure.confidence >= 60
          ? "⚡ MEDIUM"
          : marketStructure.confidence >= 40
          ? "💡 WEAK"
          : "❓ VERY WEAK";

      message += `

🏗️ <b>MARKET STRUCTURE BREAK!</b>
${signalType} STRUCTURE ${marketStructure.structureType} ${strength}

📊 <b>Entry Price:</b> ${marketStructure.price.toLocaleString()} USDT
🏗️ <b>Structure Type:</b> ${marketStructure.structureType}
🎯 <b>Take Profit:</b> ${marketStructure.takeProfit.toLocaleString()} USDT
🛡️ <b>Stop Loss:</b> ${marketStructure.stopLoss.toLocaleString()} USDT
📊 <b>Confidence:</b> ${marketStructure.confidence.toFixed(1)}%
      `;
    }

    // Add summary if multiple signals
    if (signalCount > 1) {
      message += `

🎯 <b>MULTIPLE CONFIRMATIONS DETECTED!</b>
📊 <b>Total Signals:</b> ${signalCount}
🔥 <b>High Probability Setup</b>
      `;
    }

    message += `

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
<i>⚠️ This is not financial advice. Trade at your own risk.</i>
    `;

    await this.sendMessage(message.trim());
  }

  /**
   * Test if the bot can send messages
   */
  async testConnection(): Promise<boolean> {
    try {
      await this.sendMessage("🧪 Bot connection test successful!");
      return true;
    } catch (error) {
      console.error("Telegram connection test failed:", error);
      return false;
    }
  }
}
